apiVersion: apps/v1
kind: Deployment
metadata:
  name: lieutenant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lieutenant-api
  template:
    metadata:
      labels:
        name: lieutenant-api
    spec:
      serviceAccountName: lieutenant-api
      containers:
        - name: lieutenant-operator
          image: docker.io/projectsyn/lieutenant-api:latest
          command:
          - lieutenant-api
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STEWARD_IMAGE
              value: docker.io/projectsyn/steward:latest
