kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lieutenant-api
  labels:
    app.kubernetes.io/name: lieutenant-api
    app.kubernetes.io/part-of: project-syn
subjects:
- kind: ServiceAccount
  name: lieutenant-api
roleRef:
  kind: Role
  name: lieutenant-api
  apiGroup: rbac.authorization.k8s.io
