apiVersion: v1
kind: Service
metadata:
  name: lieutenant-api
  labels:
    app.kubernetes.io/name: lieutenant-api
    app.kubernetes.io/part-of: project-syn
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lieutenant-api
  ports:
  - name: http
    port: 80
    targetPort: http
