apiVersion: v1
kind: Service
metadata:
  name: lieutenant-api
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: lieutenant-api
  type: ClusterIP
